### ISSUE TITLE
希望加入!

### ISSUE THREAD

**Issue by ayuan-gy** [fengxinhhh/Concis#16]
希望能够有机会参与到这个项目中来，40257315@qq.com

**Comment by fengxinhhh** [comment]
你好，需要你的加入~
关于贡献指南:http://react-view-ui.com:92/#/guide/zcontribute

具体的话，对于前几次还是先fork仓库然后有几次pr效果不错的话就一起做吧，目前也是只有两位同学在空余时间去做的~
