### ISSUE TITLE
分页器小bug

### ISSUE THREAD

**Issue by OuYangHuaQing** [fengxinhhh/Concis#2]
分页器Pagination设置15条/页或更多时中间的数字显示不正确
![image](https://user-images.githubusercontent.com/77443387/170173174-1d007b2a-a312-4b61-ba2d-7ff024b887c7.png)
![image](https://user-images.githubusercontent.com/77443387/170173209-ee13be67-34fb-4cf1-8c1c-4f32b7496de2.png)

**Comment by fengxinhhh** [comment]
您好，很感谢您关注并使用了React-View-UI。
的确复现到了邮件所阐述的问题，官方文档和npm线上版本已经修复，并且对于一些其他功能进行了优化升级：


1.分页器下拉增加选中效果；
2.修复输入框式分页器输入回车跳转bug；
***@***.***直接使用React-View-UI。


恳请留下联系方式，更方便以后问题的回馈，让组件库越来越完善~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fengxinhhh/React-View-UI-fs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月25日(星期三) 中午11:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[fengxinhhh/React-View-UI-fs] 分页器小bug (Issue #2)





 
分页器Pagination设置15条/页或更多时中间的数字显示不正确

**Comment by OuYangHuaQing** [comment]
你好，我的联系方式是qq：1501280663
好像刚刚修改完之后有新的问题了，方便加qq联系吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fengxinhhh/React-View-UI-fs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月25日(星期三) 晚上6:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fengxinhhh/React-View-UI-fs] 分页器小bug (Issue #2)





 您好，很感谢您关注并使用了React-View-UI。 
 的确复现到了邮件所阐述的问题，官方文档和npm线上版本已经修复，并且对于一些其他功能进行了优化升级： 
 
 
 1.分页器下拉增加选中效果； 
 2.修复输入框式分页器输入回车跳转bug； 
 ***@***.***直接使用React-View-UI。 
 
 
 恳请留下联系方式，更方便以后问题的回馈，让组件库越来越完善~ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "fengxinhhh/React-View-UI-fs"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年5月25日(星期三) 中午11:25 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[fengxinhhh/React-View-UI-fs] 分页器小bug (Issue #2) 
 
 
 
 
 
   
 分页器Pagination设置15条/页或更多时中间的数字显示不正确
