### ISSUE TITLE
[InputPro]点击被禁用的选项后气泡直接消失是合理的吗？

### ISSUE THREAD

**Issue by FriedRiceNoodles** [fengxinhhh/Concis#78]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/53017934/193234662-fa2f050e-9161-4247-b06e-fca597c0ee3c.png">

**Comment by fengxinhhh** [comment]
不合理，是个bug，建议直接提个pr~

**Comment by FriedRiceNoodles** [comment]
> 不合理，是个bug，建议直接提个pr~

可以的，但是我遇到的build失败的问题似乎还没得到解决:)

**Comment by fengxinhhh** [comment]
fix~

commit: 
https://github.com/fengxinhhh/Concis/commit/314de72cf872d535a0627547cafdf3e9d9b0f59b

close.
