### ISSUE TITLE
建议使用更轻量的 @ant-design/icons 代替 antd

### ISSUE THREAD

**Issue by wuwenbang** [fengxinhhh/Concis#8]
我看到 package.json 里依赖 antd，如果项目中只使用 antd icons 的话，建议使用更轻量的 @ant-design/icons 代替 antd 包。

**Comment by fengxinhhh** [comment]
是的，这一点确实没考虑到，因为最早其实是想选择一些组件基于antd去二次封装的，后来写着写着其实就依赖图标库~
感谢你的建议！

**Comment by fengxinhhh** [comment]
看了下项目，直接把antd依赖去掉就好了~更新了
