### ISSUE TITLE
TimePicker选择相同的时间点击确定不会隐藏

### ISSUE THREAD

**Issue by luke358** [fengxinhhh/Concis#92]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/48149577/202191690-af7e98c5-1940-4c11-a762-d3d7ebbb31d9.png">
应该是这个依赖react判断前后相等的问题 [L51](https://github.com/fengxinhhh/Concis/blob/master/packages/concis-react/src/TimePicker/index.tsx#L51)

## 解决方案
通过ref强制关闭 Popover

**Comment by fengxinhhh** [comment]
感谢提出，已更正，另外还发现Popover的一些问题，一起改了~

欢迎一起pr呀哈~

**Comment by luke358** [comment]
> 感谢提出，已更正，另外还发现Popover的一些问题，一起改了~
> 
> 欢迎一起pr呀哈~

老哥，我微信加你了 luke358
